using System;
using UnityEngine.InputSystem;
using StellarMass.InputManagement.UnityGenerated;

namespace StellarMass.InputManagement
{
    ///<summary>
    /// This class was automatically generated by InputScriptGenerator.
    ///</summary>
    public class GameplayActions : InputActions.IGameplayActions
    {
        public event Action<InputAction.CallbackContext> @OnThrust;
        public event Action<InputAction.CallbackContext> @OnShoot;
        public event Action<InputAction.CallbackContext> @OnHyperspace;
        public event Action<InputAction.CallbackContext> @OnTurn;
        public event Action<InputAction.CallbackContext> @OnPause;
        
        void InputActions.IGameplayActions.OnThrust(InputAction.CallbackContext context) => OnThrust?.Invoke(context);
        void InputActions.IGameplayActions.OnShoot(InputAction.CallbackContext context) => OnShoot?.Invoke(context);
        void InputActions.IGameplayActions.OnHyperspace(InputAction.CallbackContext context) => OnHyperspace?.Invoke(context);
        void InputActions.IGameplayActions.OnTurn(InputAction.CallbackContext context) => OnTurn?.Invoke(context);
        void InputActions.IGameplayActions.OnPause(InputAction.CallbackContext context) => OnPause?.Invoke(context);
    }
}
